/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApprocheRouteImport } from './routes/approche'
import { Route as CliniqueRouteImport } from './routes/clinique'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as RendezVousRouteImport } from './routes/rendez-vous'
import { Route as ResultatsRouteImport } from './routes/resultats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SoinsRouteImport } from './routes/soins'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActiviteRouteImport } from './routes/admin.activite'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminDevisRouteImport } from './routes/admin.devis'
import { Route as AdminEquipeRouteImport } from './routes/admin.equipe'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminRevenusRouteImport } from './routes/admin.revenus'
import { Route as AdminSuivisRouteImport } from './routes/admin.suivis'
import { Route as AdminTraitementsRouteImport } from './routes/admin.traitements'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminDemandesIndexRouteImport } from './routes/admin.demandes.index'
import { Route as AdminDemandesIdRouteImport } from './routes/admin.demandes.$id'
import { Route as AdminPatientsIndexRouteImport } from './routes/admin.patients.index'
import { Route as AdminPatientsIdRouteImport } from './routes/admin.patients.$id'
import { Route as AdminDevisIdPrintRouteImport } from './routes/admin.devis.$id.print'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprocheRoute = ApprocheRouteImport.update({
  id: '/approche',
  path: '/approche',
  getParentRoute: () => rootRouteImport,
} as any)
const CliniqueRoute = CliniqueRouteImport.update({
  id: '/clinique',
  path: '/clinique',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const RendezVousRoute = RendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatsRoute = ResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SoinsRoute = SoinsRouteImport.update({
  id: '/soins',
  path: '/soins',
  getParentRoute: () => rootRouteImport,
} as any)
const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActiviteRoute = AdminActiviteRouteImport.update({
  id: '/activite',
  path: '/activite',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevisRoute = AdminDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipeRoute = AdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenusRoute = AdminRevenusRouteImport.update({
  id: '/revenus',
  path: '/revenus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuivisRoute = AdminSuivisRouteImport.update({
  id: '/suivis',
  path: '/suivis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTraitementsRoute = AdminTraitementsRouteImport.update({
  id: '/traitements',
  path: '/traitements',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemandesIndexRoute = AdminDemandesIndexRouteImport.update({
  id: '/demandes/',
  path: '/demandes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemandesIdRoute = AdminDemandesIdRouteImport.update({
  id: '/demandes/$id',
  path: '/demandes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsIndexRoute = AdminPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsIdRoute = AdminPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevisIdPrintRoute = AdminDevisIdPrintRouteImport.update({
  id: '/$id/print',
  path: '/$id/print',
  getParentRoute: () => AdminDevisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/approche': typeof ApprocheRoute
  '/clinique': typeof CliniqueRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/rendez-vous': typeof RendezVousRoute
  '/resultats': typeof ResultatsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soins': typeof SoinsRoute
  '/temoignages': typeof TemoignagesRoute
  '/videos': typeof VideosRoute
  '/admin/activite': typeof AdminActiviteRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/devis': typeof AdminDevisRouteWithChildren
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/revenus': typeof AdminRevenusRoute
  '/admin/suivis': typeof AdminSuivisRoute
  '/admin/traitements': typeof AdminTraitementsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/demandes/$id': typeof AdminDemandesIdRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/demandes/': typeof AdminDemandesIndexRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/admin/devis/$id/print': typeof AdminDevisIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approche': typeof ApprocheRoute
  '/clinique': typeof CliniqueRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/rendez-vous': typeof RendezVousRoute
  '/resultats': typeof ResultatsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soins': typeof SoinsRoute
  '/temoignages': typeof TemoignagesRoute
  '/videos': typeof VideosRoute
  '/admin/activite': typeof AdminActiviteRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/devis': typeof AdminDevisRouteWithChildren
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/revenus': typeof AdminRevenusRoute
  '/admin/suivis': typeof AdminSuivisRoute
  '/admin/traitements': typeof AdminTraitementsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/demandes/$id': typeof AdminDemandesIdRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/demandes': typeof AdminDemandesIndexRoute
  '/admin/patients': typeof AdminPatientsIndexRoute
  '/admin/devis/$id/print': typeof AdminDevisIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/approche': typeof ApprocheRoute
  '/clinique': typeof CliniqueRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/rendez-vous': typeof RendezVousRoute
  '/resultats': typeof ResultatsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soins': typeof SoinsRoute
  '/temoignages': typeof TemoignagesRoute
  '/videos': typeof VideosRoute
  '/admin/activite': typeof AdminActiviteRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/devis': typeof AdminDevisRouteWithChildren
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/revenus': typeof AdminRevenusRoute
  '/admin/suivis': typeof AdminSuivisRoute
  '/admin/traitements': typeof AdminTraitementsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/demandes/$id': typeof AdminDemandesIdRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/demandes/': typeof AdminDemandesIndexRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/admin/devis/$id/print': typeof AdminDevisIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/approche'
    | '/clinique'
    | '/contact'
    | '/faq'
    | '/rendez-vous'
    | '/resultats'
    | '/sitemap.xml'
    | '/soins'
    | '/temoignages'
    | '/videos'
    | '/admin/activite'
    | '/admin/agenda'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/devis'
    | '/admin/equipe'
    | '/admin/marketing'
    | '/admin/notifications'
    | '/admin/parametres'
    | '/admin/pipeline'
    | '/admin/revenus'
    | '/admin/suivis'
    | '/admin/traitements'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/demandes/$id'
    | '/admin/patients/$id'
    | '/admin/demandes/'
    | '/admin/patients/'
    | '/admin/devis/$id/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approche'
    | '/clinique'
    | '/contact'
    | '/faq'
    | '/rendez-vous'
    | '/resultats'
    | '/sitemap.xml'
    | '/soins'
    | '/temoignages'
    | '/videos'
    | '/admin/activite'
    | '/admin/agenda'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/devis'
    | '/admin/equipe'
    | '/admin/marketing'
    | '/admin/notifications'
    | '/admin/parametres'
    | '/admin/pipeline'
    | '/admin/revenus'
    | '/admin/suivis'
    | '/admin/traitements'
    | '/blog/$slug'
    | '/admin'
    | '/blog'
    | '/admin/demandes/$id'
    | '/admin/patients/$id'
    | '/admin/demandes'
    | '/admin/patients'
    | '/admin/devis/$id/print'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/approche'
    | '/clinique'
    | '/contact'
    | '/faq'
    | '/rendez-vous'
    | '/resultats'
    | '/sitemap.xml'
    | '/soins'
    | '/temoignages'
    | '/videos'
    | '/admin/activite'
    | '/admin/agenda'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/devis'
    | '/admin/equipe'
    | '/admin/marketing'
    | '/admin/notifications'
    | '/admin/parametres'
    | '/admin/pipeline'
    | '/admin/revenus'
    | '/admin/suivis'
    | '/admin/traitements'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/demandes/$id'
    | '/admin/patients/$id'
    | '/admin/demandes/'
    | '/admin/patients/'
    | '/admin/devis/$id/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApprocheRoute: typeof ApprocheRoute
  CliniqueRoute: typeof CliniqueRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  RendezVousRoute: typeof RendezVousRoute
  ResultatsRoute: typeof ResultatsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoinsRoute: typeof SoinsRoute
  TemoignagesRoute: typeof TemoignagesRoute
  VideosRoute: typeof VideosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approche': {
      id: '/approche'
      path: '/approche'
      fullPath: '/approche'
      preLoaderRoute: typeof ApprocheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinique': {
      id: '/clinique'
      path: '/clinique'
      fullPath: '/clinique'
      preLoaderRoute: typeof CliniqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendez-vous': {
      id: '/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/rendez-vous'
      preLoaderRoute: typeof RendezVousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultats': {
      id: '/resultats'
      path: '/resultats'
      fullPath: '/resultats'
      preLoaderRoute: typeof ResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soins': {
      id: '/soins'
      path: '/soins'
      fullPath: '/soins'
      preLoaderRoute: typeof SoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activite': {
      id: '/admin/activite'
      path: '/activite'
      fullPath: '/admin/activite'
      preLoaderRoute: typeof AdminActiviteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devis': {
      id: '/admin/devis'
      path: '/devis'
      fullPath: '/admin/devis'
      preLoaderRoute: typeof AdminDevisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipe': {
      id: '/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AdminEquipeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenus': {
      id: '/admin/revenus'
      path: '/revenus'
      fullPath: '/admin/revenus'
      preLoaderRoute: typeof AdminRevenusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suivis': {
      id: '/admin/suivis'
      path: '/suivis'
      fullPath: '/admin/suivis'
      preLoaderRoute: typeof AdminSuivisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/traitements': {
      id: '/admin/traitements'
      path: '/traitements'
      fullPath: '/admin/traitements'
      preLoaderRoute: typeof AdminTraitementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/demandes/': {
      id: '/admin/demandes/'
      path: '/demandes'
      fullPath: '/admin/demandes/'
      preLoaderRoute: typeof AdminDemandesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demandes/$id': {
      id: '/admin/demandes/$id'
      path: '/demandes/$id'
      fullPath: '/admin/demandes/$id'
      preLoaderRoute: typeof AdminDemandesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients/': {
      id: '/admin/patients/'
      path: '/patients'
      fullPath: '/admin/patients/'
      preLoaderRoute: typeof AdminPatientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients/$id': {
      id: '/admin/patients/$id'
      path: '/patients/$id'
      fullPath: '/admin/patients/$id'
      preLoaderRoute: typeof AdminPatientsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devis/$id/print': {
      id: '/admin/devis/$id/print'
      path: '/$id/print'
      fullPath: '/admin/devis/$id/print'
      preLoaderRoute: typeof AdminDevisIdPrintRouteImport
      parentRoute: typeof AdminDevisRoute
    }
  }
}

interface AdminDevisRouteChildren {
  AdminDevisIdPrintRoute: typeof AdminDevisIdPrintRoute
}

const AdminDevisRouteChildren: AdminDevisRouteChildren = {
  AdminDevisIdPrintRoute: AdminDevisIdPrintRoute,
}

const AdminDevisRouteWithChildren = AdminDevisRoute._addFileChildren(
  AdminDevisRouteChildren,
)

interface AdminRouteChildren {
  AdminActiviteRoute: typeof AdminActiviteRoute
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDevisRoute: typeof AdminDevisRouteWithChildren
  AdminEquipeRoute: typeof AdminEquipeRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminRevenusRoute: typeof AdminRevenusRoute
  AdminSuivisRoute: typeof AdminSuivisRoute
  AdminTraitementsRoute: typeof AdminTraitementsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDemandesIdRoute: typeof AdminDemandesIdRoute
  AdminPatientsIdRoute: typeof AdminPatientsIdRoute
  AdminDemandesIndexRoute: typeof AdminDemandesIndexRoute
  AdminPatientsIndexRoute: typeof AdminPatientsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActiviteRoute: AdminActiviteRoute,
  AdminAgendaRoute: AdminAgendaRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDevisRoute: AdminDevisRouteWithChildren,
  AdminEquipeRoute: AdminEquipeRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminRevenusRoute: AdminRevenusRoute,
  AdminSuivisRoute: AdminSuivisRoute,
  AdminTraitementsRoute: AdminTraitementsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDemandesIdRoute: AdminDemandesIdRoute,
  AdminPatientsIdRoute: AdminPatientsIdRoute,
  AdminDemandesIndexRoute: AdminDemandesIndexRoute,
  AdminPatientsIndexRoute: AdminPatientsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApprocheRoute: ApprocheRoute,
  CliniqueRoute: CliniqueRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  RendezVousRoute: RendezVousRoute,
  ResultatsRoute: ResultatsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoinsRoute: SoinsRoute,
  TemoignagesRoute: TemoignagesRoute,
  VideosRoute: VideosRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
